name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install PyTorch CPU
        run: |
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

      - name: Install Project and Test Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_API_BASE: ${{ secrets.TEST_API_BASE }}
          TEST_MODEL: ${{ secrets.TEST_MODEL }}
        run: pytest -v --tb=short
